name = "andreysergeevich"
compatibility_date = "2025-08-29"
pages_build_output_dir = "dist-andrey"

[vars]
SITE_URL = "https://andreysergeevich.me"

# KV namespaces for rate limiting and analytics
[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "your-rate-limit-namespace-id"

[[kv_namespaces]]
binding = "VISITS"
id = "your-visits-namespace-id"

[[kv_namespaces]]
binding = "LEADERBOARD"
id = "your-leaderboard-namespace-id"

[[kv_namespaces]]
binding = "ANALYTICS"
id = "your-analytics-namespace-id"

# D1 database for guestbook
[[d1_databases]]
binding = "DB"
database_name = "andrey_guestbook"
database_id = "your-guestbook-database-id"

# R2 bucket for media storage
[[r2_buckets]]
binding = "MEDIA"
bucket_name = "andrey-media"

# Queue for event processing
[[queues.producers]]
binding = "EVENT_QUEUE"
queue = "andrey-site-events"
