name = "jw-site"
compatibility_date = "2025-08-29"

# Cloudflare Pages project build output
pages_build_output_dir = "dist"

[vars]
# Production site URL - update this with your custom domain later
SITE_URL = "https://jw-site-7q2.pages.dev"

# If you later add KV / D1 / R2 bindings, document them here.

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "33fcae0c755840f996bfbb3ca3f9394f"
preview_id = "ec6a2c7250064a89b0fa71accdaf51ba"
# Namespace used for rate limiting buckets (keys rl:*). Previously VISITS; renamed for clarity.

[[d1_databases]]
binding = "DB"
database_name = "guestbook_demo"
database_id = "40c9d6ea-ccb2-4fce-a2d7-339199841004"

# Turnstile environment variables (set in Pages dashboard, not stored here):
# - TURNSTILE_SECRET_KEY (Secret)
# - PUBLIC_TURNSTILE_SITE_KEY (Build variable)

# Additional KV namespaces for game features
[[kv_namespaces]]
binding = "LEADERBOARD"
id = "4792010013254ed7815b2d66adb9a50e"
preview_id = "508f61d2b5d6442bae53fbe541698360"

[[kv_namespaces]]
binding = "ANALYTICS"
id = "3dd7938561f5402bb41760edda181030"
preview_id = "64323cab0ce447d182e8a5038461e6d3"

# Workflows configuration (implemented as functions for now)
# These will be converted to proper workflows when Cloudflare Workflows supports them
# [[workflows]]
# name = "game-score-processor"
# file = "workflows/game-score-processor.ts"
# binding = "GAME_WORKFLOW"

# [[workflows]]
# name = "guestbook-cleanup"
# file = "workflows/guestbook-cleanup.ts"
# binding = "CLEANUP_WORKFLOW"
