name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint || echo "(lint warnings ignored for now)"
      - name: Validate content & generate MCP settings
        run: SITE_URL="https://preview.example" npm run build:cf --dry-run || npm run prebuild
      - name: Build
        env:
          SITE_URL: https://preview.example
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
